tasks:
  - name: Execute Docker compose up
    before: |
      sudo curl -o /usr/local/bin/docker-compose -fsSL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-$(uname -m)
      echo "alias dc=docker-compose" >> ~/.bash_aliases
    init: |
      cp .env.sample .env
    command: >
      docker-compose up -d &&
      docker-compose exec api python3 /usr/src/app/utils/download.py tokenizer 7B

# Configure vscode
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - eamodio.gitlens
    - ikappas.composer
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - MehediDracula.php-namespace-resolver
    - wmaurer.change-case
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
    - rangav.vscode-thunder-client
